### ISSUE TITLE
Demo removes red border if email set and option select is modified.

### ISSUE THREAD

**Issue by rouilj** [aarongustafson/form-required-if#1]
Thanks for the component, but I think there is a bug.

If I add the email: foo@bar.edu, I see the first three depends fields with red border.
If I change the select to any value except option3, the "Depends on email or select"
removes the red border even if the email is still filled in.

Also you might want to mention that an 'and 'of two fields (rather than or) can be done by nesting:

```
			<form-required-if conditions="email=*">
                            <form-required-if conditions="choose=3" indicator="*" indicator-position="before">
				<label>Depends on email or select
					<input name="dep2" aria-describedby="dep2-description">
					<small id="dep2-description">This field is required if the email field is filled out or if the <code>select</code> has Option 3 chosen. It uses a custom indicator placed before the label text.</small>
				</label>
                            </form-required-if>
			</form-required-if>
```

which I think works.

**Comment by aarongustafson** [comment]
Good catch on the bug. I’ll get that sorted.

I hadn’t considered nesting (I’d been pondering &&), but that’s an interesting approach.

**Comment by aarongustafson** [comment]
Got it sorted. I’d done some optimization by reducing the scope of the conditions to only the current field, but that introduced this bug.
