### ISSUE TITLE
Little wierdness with marker when input is embedded in label and label text surrounded by span

### ISSUE THREAD

**Issue by rouilj** [aarongustafson/form-required-if#3]
I was trying out a few variations (see: https://codepen.io/rouilj/pen/XWLzvOQ) and I noticed that

```
<form-required-if conditions="email=*" indicator="*"><br>
  <label>
    <span>a label</span>
    <input type="text">
  </label>
</form-required-if>
```
places the marker before the span'ed text label. But:
```
<form-required-if conditions="email=*" indicator="*"><br>
  <label>
    a label
    <input type="text">
  </label>
</form-required-if>
```
places it after the text label (and the label is snugged up to the input, unlike the span case where there is
some space (maybe 1em??).

Also IIRC some screen readers/assistive devices have issues when the label wraps the input and
would prefer the markup to be:
```
<form-required-if conditions="email=*" indicator="<b>*</b>">
   <label for="text">Required if there’s an email value</label>
   <input type="text" id="text" name="depends-on-email-or-test">
</form-required-if>
```
This works and also puts the indicator after the label.

Also I just spent over an hour trying to get codepen to play nice and import the component directly from
github using cdn.rawgit.com but I ended up having to copy/paste your component, so it will stay broken until
I repaste.

**Comment by aarongustafson** [comment]
> I was trying out a few variations…

I’ll play with some other markup patterns to see if I can come up with a more robust insertion process that gracefully handles other elements being inside the `label`.

> Also IIRC some screen readers/assistive devices have issues when the label wraps the input

Do you have a resource that backs this up? For a long time I used the separate approach for labels & fields on everything but radio & checkbox inputs. IE was the only browser that had issues with implicit association (as opposed to explicit association via `for`), but that was back in the IE7 days. I don’t believe it’s an issue now, but if you can point me to a reputable source that indicates the contrary, I’m keen to read it.

**Comment by rouilj** [comment]
I think you are correct. All browsers do the right thing with implicit linking. (Time to revise my
expectation there.)

Not all assistive tech does. I am looking at: https://a11ysupport.io/tests/html_label_element_implicit (updated feb 2024).

It looks like the accessible label is reported ok. However for Dragon and Voice control on a mac you
can't say "click label".

If you use `for` on the label and `id` on the input to explicitly link them, it looks
like it works even if nested. https://a11ysupport.io/tests/html_label_element_explicit.

No idea if there is much market share for the two broken AT programs, So it might
not be a problem.

**Comment by rouilj** [comment]
Did 682d89958fef handle the wierd placement of the required marker that triggered this issue?

**Comment by aarongustafson** [comment]
Yes. See the updated demo.
