### ISSUE TITLE
Indicator can include javascript and be executed

### ISSUE THREAD

**Issue by rouilj** [aarongustafson/form-required-if#4]
One thought crossed my mind about the indicator allowing html. Could a script tag be used there?
```
indicator="<img src='x' onerror='alert(1)'> <script>alert('hello')</script>"
```
Script is blocked, but [img works to smuggle in js](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#security_considerations).
 
See the img script (next to last example on https://codepen.io/rouilj/pen/XWLzvOQ) working.

Thoughts?

**Comment by aarongustafson** [comment]
While I appreciate you calling out the potential issue here, I’m not terribly concerned about this as a vector for abuse as it would be the page author who uses the custom element, not user generated code. If it continues to come up, I will look to add some defense against it.
